server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: products-service
          uri: lb://products-service/
          predicates:
            - Path=/product/**
        - id: stock-service
          uri: lb://stock-service/
          predicates:
            - Path=/stock/**
        - id: category-service
          uri: lb://category-service/
          predicates:
            - Path=/category/**
